From 0000000000000000000000000000000000000000 Mon Sep 17 00:00:00 2001
From: Fedora Python maintainers <python-devel@lists.fedoraproject.org>
Date: Wed, 15 Jul 2020 15:25:00 +0200
Subject: [PATCH] 00142-skip-failing-pty-tests-in-rpmbuild.patch

00142 #
Some pty tests fail when run in mock (rhbz#714627):
---
 Lib/test/test_openpty.py | 1 +
 Lib/test/test_pty.py     | 1 +
 2 files changed, 2 insertions(+)

diff --git a/Lib/test/test_openpty.py b/Lib/test/test_openpty.py
index 4b34b3a3c77..a1a5832a7ad 100644
--- a/Lib/test/test_openpty.py
+++ b/Lib/test/test_openpty.py
@@ -8,6 +8,7 @@ if not hasattr(os, "openpty"):
 
 
 class OpenptyTest(unittest.TestCase):
+    @unittest._skipInRpmBuild('sometimes fails in Koji, possibly due to a mock issue (rhbz#714627)')
     def test(self):
         master, slave = os.openpty()
         self.addCleanup(os.close, master)
diff --git a/Lib/test/test_pty.py b/Lib/test/test_pty.py
index 0eb31fdaf70..9f12a51a50e 100644
--- a/Lib/test/test_pty.py
+++ b/Lib/test/test_pty.py
@@ -125,6 +125,7 @@ class PtyTest(unittest.TestCase):
         os.close(master_fd)
 
 
+    @unittest._skipInRpmBuild('sometimes fails in Koji, possibly due to a mock issue (rhbz#714627)')
     def test_fork(self):
         debug("calling pty.fork()")
         pid, master_fd = pty.fork()
